name: interactive_pdf_viewer
description: A Flutter package for displaying PDFs with the ability to retrieve sentences by tapping on their position.
version: 0.1.0
homepage: https://github.com/bjorndonald/interactive_pdf_viewer
repository: https://github.com/bjorndonald/interactive_pdf_viewer.git
issue_tracker: https://github.com/bjorndonald/interactive_pdf_viewer/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.0
  pdf_text: ^0.5.0
  path_provider: ^2.0.11
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# flutter:
#   assets:
#     - assets/

# Additional metadata
topics:
  - pdf
  - viewer
  - interactive
  - text-selection
  - flutter

screenshots:
  - description: Interactive PDF Viewer with text selection
    path: assets/screenshots/screenshot1.png
  - description: PDF Viewer with page navigation
    path: assets/screenshots/screenshot2.png

# Documentation
documentation: https://github.com/bjorndonald/interactive_pdf_viewer/blob/main/README.md

# License
license: MIT

# Author information
author: Bjorndornald <bjorndornald@gmail.com>

# Platform support
platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:


