name: interactive_pdf_viewer
description: A Flutter package for displaying PDFs with interactive features including text selection, page tracking, quote management, minimizable viewer, and custom UI controls. Features include individual quote removal, floating minimized view, and programmatic control.
version: 0.2.7
homepage: https://github.com/bjorndonald/interactive_pdf_viewer
repository: https://github.com/bjorndonald/interactive_pdf_viewer.git
issue_tracker: https://github.com/bjorndonald/interactive_pdf_viewer/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  http: ^0.13.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/screenshots/
  plugin:
    platforms:
      android:
        package: com.bjorncode.interactive_pdf_viewer
        pluginClass: InteractivePDFViewerPlugin
      ios:
        pluginClass: InteractivePDFViewerPlugin

# Additional metadata
topics:
  - pdf
  - interactive
  - text-selection
  - minimizable
  - flutter

screenshots:
  - description: Interactive PDF Viewer with minimizable interface and quote management
    path: assets/screenshots/screenshot_1.png
  - description: PDF Viewer with floating minimized view and controls
    path: assets/screenshots/screenshot_2.png

# Documentation
documentation: https://github.com/bjorndonald/interactive_pdf_viewer/blob/main/README.md

# License
license: MIT

# Platform support
platforms:
  android:
  ios:
  web:
  windows:
  macos:


